<?= $this->render('/includes/header.phtml') ?>

            <td>
                <br/>
                 <h2 style="font-size: 20pt; font-style: italic; text-transform: capitalize;" align="center">
                     <font style=" color: olive; font-style: italic; font-size: 30pt;">
                        Vote Needed
                     </font>
                </h2>
            </td>
         </tr>
    </table>
    <table width="800" align="center">
	  <tr>
	  	<td style='text-align:center;font-size:18pt;'>
	  		You haven't voted on an item that you have purchased.<br/>
	  		To continue, you must vote.
	  	</td>
	  </tr>
	</table>
	<table width="800" align="center">
  		<tr>
  			<td>
  			Here is the content you purchased <br/>
  			Title: <?=$this->vote['title']?><br/>
  			Description: <?=$this->vote['description']?>
           <a href="thumbUp/purchase/<?=$this->purchase_id?>/content/<?=$this->vote['content_id']?>"><img border="0" src="http://t2.gstatic.com/images?q=tbn:Uv4SXAOqDQtPAM:http://www.forum.nokia.com/piazza/wiki/images/3/34/Thumbs_up_icon_sm.jpg" alt="" width="30px"/></a><a href="thumbDown/purchase/<?=$this->purchase_id?>/content/<?=$this->vote['content_id']?>"><img border="0" src="http://t0.gstatic.com/images?q=tbn:XeZw7-CkdZ-5MM:http://www.dreamstime.com/thumb-down-gesture-icon-vector-thumb9227628.jpg" alt="" width="30px"/></a>  			
  			</td>
  		</tr>
	</table>


</body>
</html>