<html>
<head>
<title>This is your site.</title>
<link rel="stylesheet" href="/Red/css/style.css" type="text/css" media="screen" />
<script language="javascript" type="text/javascript" >
<!-- hide

function jumpto(x){

if (document.form1.jumpmenu.value != "null") {
document.location.href = x
}
}

// end hide -->
</script>

</head>
<body>
        <table width="800" align="center">
            <? if($_SESSION['is_logged_in'] == FALSE) :?>
        <tr style="font-size: 10pt; float: left;">
            <td>
                <a href="/Red/public/user/login">Member Login</a> -
                <a href="/Red/public/user/register" >Sign Up</a>
            </td>
        </tr>
        <? else :?>
        <tr style="font-size: 10pt; float: left;">
            <td>
                <a href="/Red/public/user/profile/user/<?=$_SESSION['user']['user_id']?>">My Profile</a><a style=" padding-left: 10px;" href="/Red/public/content/add">Add Content</a>
            </td>
        </tr>
        <tr style="float: right; font-size: 10pt;">
            <td>
                <a href="/Red/public/user/logout">Logout</a>
            </td>
        </tr>
        <? endif;?>
    </table>
    <table width="800" align="center">
        <tr>
        <hr width="800"/>
        </tr>
        <tr style="font-size: 10pt;">
            <td width="150">
                <a href="/Red/public/content/index"><img border="0" src="http://t0.gstatic.com/images?q=tbn:QcMQqlmgL14mlM:http://nubianem.tripod.com/imagelib/sitebuilder/layout/logo.gif" alt="#" width="150"/></a>
            </td>