
<?= $this->render('/includes/header.phtml') ?>

            <td>
                <br/>
                 <h2 style="font-size: 20pt; font-style: italic; text-transform: capitalize;" align="center">
                     <font style=" color: olive; font-style: italic; font-size: 30pt;">
                        Member Login
                     </font>
                </h2>
            </td>
         </tr>
    </table>
    <table width="800" align="center">
	  <tr>
	  	<td style='text-align:center;font-size:18pt;'>
	  		<? if ($this->message != array()) :?>
	  		<?=$this->message[0];?>
	  		<? endif;?>
	  		<? if (Red_User::$error) :?>
	  		<?=Red_User::$error?>
	  		<? endif;?>
	  	</td>
	  </tr>
	</table>
	<table width="800" align="center">
	  <tr>
	  	<td style='text-align:center;font-size:18pt;'>
	  		<?php echo $this->form;?>
	  	</td>
	  </tr>
	</table>


</body>
</html>