
<?= $this->render('/includes/header.phtml') ?>

            <td>
                <br/>
                 <h2 style="font-size: 20pt; font-style: italic; text-transform: capitalize;" align="center">
                     <font style=" color: olive; font-style: italic; font-size: 30pt;">
                        Member Registration
                     </font>
                </h2>
            </td>
         </tr>
    </table>
    <table width="800" align="center">
	  <tr>
	  	<td style='text-align:left;font-size:18pt;padding-left:240px;'>
	  		<?php echo $this->form;?>
	  	</td>
	  </tr>
	</table>
	<table width="800" align="center">
  		<tr>
  			
  		</tr>
	</table>


</body>
</html>